#!/bin/bash

PYTHON=$(which python)
MAIN=src/cod.py

# Launcher for Cod

# Copyright (c) 2013, Sam Dodrill
# All rights reserved.
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

if [ -d env ]; then
    echo "--- Virtualenv found"
else
    if [ -x $(virtualenv)]; then
        echo "!!! Setting up virtual environment"
        virtualenv env
    else
        echo "!!! Virtualenv not installed"
        exit
    fi
fi

echo "--- Installing venv dependencies"
env/bin/pip install -r requirements.txt > /dev/null

echo "--- Searching for ideal Python 2 interpreter"
if [ -x "$(which python)" ]; then
    PYTHON=python2
    echo "!!! Python found"
elif [ -x "$(which python2)" ]; then
    PYTHON=python
    echo "!!! Python2 found"
else
    echo "!!! Compatible Python interpreter not found. Exiting"
    exit
fi

echo "--- Python interpreter is $PYTHON"

$PYTHON $MAIN $1

