#!/bin/bash

PYTHON=$(which python)
MAIN=src/cod.py

# Launcher for Cod

# Copyright (c) 2013, Sam Dodrill
# All rights reserved.
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

echo "--- Searching for ideal Python 2 interpreter"

if [ -x "$(which python2)" ]; then
    PYTHON=python2
    echo "!!! python2 found"
elif [ -x "$(which python)" ]; then
    PYTHON=python
    echo "!!! vanilla Python found. If this is Python 3, Cod will not work"
else
    echo "!!! Compatible Python interpreter not found. Exiting"
fi

echo "--- Python interpreter is $PYTHON"

echo "--- Searching for library dependencies"

function testmodule {
    if $PYTHON -c "import $1" > /dev/null; then
        echo "!!! library $1 found! $2 will function properly."
    else
        echo "!!! library $1 not found. Please install $1 from pip"
        exit
    fi
}

testmodule sqlite3 "Everything that uses the database"
testmodule mpd "The MPD client"
testmodule requests "The Tortoise Labs DNS client"
testmodule dns "RBLWatch DNS blacklist lookups"

$PYTHON $MAIN

