#!/bin/bash

MAIN=src/cod.py
PYTHON=python

# Launcher for Cod

# Copyright (c) 2013, Sam Dodrill
# All rights reserved.
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

function testmodule {
if $PYTHON -c "import $1" > /dev/null; then
	true
else
	echo "!!! library $1 not found. Please install $1 from system package repositories"
	exit
fi
}

echo "--- Updating niilib"
git submodule update 2> /dev/null > /dev/nul

#Download the TLD list
echo "--- Getting TLD list"

if [ -e var/tlds-alpha-by-domain.txt ]; then
	rm var/tlds-alpha-by-domain.txt
fi

wget -O var/tlds-alpha-by-domain.txt http://data.iana.org/TLD/tlds-alpha-by-domain.txt 2> /dev/null > /dev/null

echo "--- Updating GeoIP database"

wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz -O var/geoip.gz
gunzip var/geoip.gz var

if [ -d env ]; then
	echo "--- Virtualenv found"
else
	echo "!!! Setting up virtual environment"
	if [ -x "$(which virtualenv)" ]; then
		virtualenv env --python=python2.7 > /dev/null
		echo "--- Virtual environment set up"
	else
		echo "!!! Virtualenv not installed"
		exit
	fi
fi

echo "--- Installing venv dependencies"
env/bin/pip install -r requirements.txt > /dev/null

source env/bin/activate

if [ -x "$(which pypy-c)" ]; then
	PYTHON=pypy-c
	echo "!!! pypy-c found! Cod will run much faster!"
elif [ -x "$(which pypy)" ]; then
	PYTHON=pypy
	echo "!!! pypy found! Cod will run much faster!"
fi

echo "--- Cleaning up previous pyc files"
rm -rf modules/**/*.pyc
rm -rf src/**/*.pyc

$PYTHON $MAIN $1

